### ISSUE TITLE
fy + npm i -g + nvm = EACCES, permission denied

### ISSUE THREAD

**Issue by vird** [hu2prod/fy#1]
https://gist.github.com/vird/cd37688335f557d5be95b6d5fedfed83
I will remove fy from log_on_port until fixed

**Comment by machulen** [comment]
Happens only if you work as root.
Solution:
npm i -g --user root hu2prod/log_on_port#88a672fee8f1ddaf43d75a975286ca7cb25aa97a
or
npm i -g --unsafe-perm hu2prod/log_on_port#88a672fee8f1ddaf43d75a975286ca7cb25aa97a
